name: Rossmann-Sales-Prediction
on:
  push:
    branches:
      - main
jobs:
  run:
    runs-on: ubuntu-latest
    # container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: run-tests
        run: |
          python -m unittest